# Project information
site_name: viva+ Human Body Models
site_url: https://
site_description: viva+  documentation
site_author: viva+ Team

# Repository
repo_name: openvt/vivaplus
repo_url: https://virtual.openvt.eu/wp-2/viva-plus

# Copyright
copyright: Copyright &copy; 2019-2020 viva+ team

nav:
    - Home: index.md
    - User Guide:
        - Getting Started: user-guide/01-getting-started.md
        - Setting up a simulation: user-guide/10-setting-up.md
        - LS-Dyna Quick Reference: user-guide/50-lsdyna-ref.md

    - Model Documentation:
        - 'Introduction to the Models': 'model-doc/00-model-intro.md'
        - 'Anthropometry': model-doc/01-anthro.md
        - 'Model Data Structure': 'model-doc/10-model-data-structure.md'
        - 'Head': model-doc/20-head.md
        - 'Neck': 'model-doc/25-neck.md'
        - 'Upper Extremities': model-doc/30-upper-extremities.md
        - 'Thorax': model-doc/40-thorax.md
        - 'Abdomen': 'model-doc/50-abdomen.md'
        - 'Pelvis': 'model-doc/60-pelvis.md'
        - 'Lower Extremities': 'model-doc/70-lower-extremities.md'
        - 'Control Card Guidelines': 'model-doc/80-control-card-guidelines.md'
        - 'Postprocessing simulations': 'model-doc/85-Postprocessing.md'
    - Contributor Guide:
        - 'How to Contribute': 'contributor-guide/01-how-to-contribute.md'
        - 'VIVA+ Git Workflow Overview': 'contributor-guide/20-viva-git-workflow.md'
        - 'Git Basics': 'contributor-guide/22-git-basics.md'
        - 'More Git Functions': contributor-guide/25-more-git-functions.md
        - 'Git Cheatsheet': contributor-guide/29-git-cheat-sheet.md
        - 'Merging your contributiona': 'contributor-guide/50-merge-guidelines.md'
        - 'Making model releases': 'contributor-guide/60-model-release.md'
        - 'Documentation Guidelines': 'contributor-guide/70-documentation-guideliness.md'
        - 'Toolkit': 'contributor-guide/95-toolkit.md'

theme:
    name: 'material'
    palette:
        primary: 'amber'
        accent: 'teal'
    features:
      - tabs
    icon: #'images/VIRTUAL.png'
        #logo: fontawesome/brands/git-alt
        logo: fontawesome/solid/walking
        repo: fontawesome/brands/git-alt
        # Find more at https://material.io/resources/icons/
    favicon: 'images/favicon.ico'
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - bibtex:
      bib_file: "viva-refs.bib"
#          - "viva-refs-1.bib"
      cite_style: "pandoc"
#  - mknotebooks # pip install mknotebooks

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
