site_name: VIVA+ Human Body Models
site_url: https://
site_description: Project documentation
site_author: VIVA Plus Team


nav:
    - Home: index.md
    - 'User Guide':
        - 'Getting Started': 'user-guide/getting-started.md'
        - 'Model Data Structure': 'user-guide/model-data-structure.md'
    - Model Documentation:
        - Anthropometry: model-doc/anthro.md
        - Head-Neck: model-doc/head-neck.md
        - Upper Extremities: model-doc/upper-extremities.md
        - Thorax and Abdomen: model-doc/thorax-and-abdomen.md
        - Pelvis and Lower Extremities: 'model-doc/pelvis-and-lower-extremities.md'
        - Control Card Guidelines: 'model-doc/control-card-guidelines.md'
    - Contributor Guide:
        - Contribute to Documentation: contributor-guide/contribute-to-documentation.md
        - Getting Started with Git: contributor-guide/getting-started-with-git.md
        - 'Advanced Git Functions': contributor-guide/advanced-git-functions.md

theme: mkdocs

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex

plugins:
  - bibtex:
      bib_file: "viva-refs.bib"
      cite_style: "pandoc"

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
