site_name: VIVA+ Human Body Models
site_url: https://
site_description: Project documentation
site_author: VIVA Plus Team


nav:
    - Home: index.md
    - 'User Guide':
        - 'Getting Started': 'user-guide/01-getting-started.md'

    - Model Documentation:
        - 'Introduction to the Models': 'model-doc/00-model-intro.md'
        - 'Anthropometry': model-doc/01-anthro.md
        - 'Model Data Structure': 'model-doc/10-model-data-structure.md'
        - 'Head': model-doc/20-head.md
        - 'Neck': 'model-doc/25-neck.md'
        - 'Upper Extremities': model-doc/30-upper-extremities.md
        - 'Thorax': model-doc/40-thorax.md
        - 'Abdomen': 'model-doc/50-abdomen.md'
        - 'Pelvis': 'model-doc/60-pelvis.md'
        - 'Lower Extremities': 'model-doc/70-lower-extremities.md'
        - Control Card Guidelines: 'model-doc/80-control-card-guidelines.md'
    - Contributor Guide:
        - 'How to Contribute': contributor-guide/01-how-to-contribute.md
        - 'Git Basics and Collaborative Development': contributor-guide/02-git-basics.md
        - 'Postprocessing simulations': 'contributor-guide/10-Postprocessing.md'
        - 'Advanced Git Functions': contributor-guide/50-advanced-git-functions.md

theme:
    name: 'material'
    palette:
        primary: 'blue grey'
        accent: 'yellow'
    logo: #'images/VIRTUAL.png'
        icon: 'directions_walk'
        # Find more at https://material.io/resources/icons/
    favicon: 'images/favicon.ico'
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex
  - admonition

plugins:
  - bibtex:
      bib_file: "viva-refs.bib"
#          - "viva-refs-1.bib"
      cite_style: "pandoc"

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
