site_name: VIVA Plus Human Body Models
site_url: https://
site_description: Project documentation
site_author: VIVA Plus Team


nav:
    - Home: index.md
    - Users Guide:
        - Getting Started: user-guide/getting-started.md
    - Model:
        - Anthropometry: model-doc/anthro.md
    - Contributors Guide:
        - Getting Started with Git: contributor-guide/getting-started-with-git.md
        - Contribute to Documentation: contributor-guide/contribute-to-documentation.md
    
