site_name: VIVA+ Human Body Models
site_url: https://
site_description: Project documentation
site_author: VIVA Plus Team


nav:
    - Home: index.md
    - 'User Guide':
        - 'Getting Started': 'user-guide/01-getting-started.md'
        - 'Model Data Structure': 'user-guide/02-model-data-structure.md'
    - Model Documentation:
        - Anthropometry: model-doc/01-anthro.md
        - Head-Neck: model-doc/02-head-neck.md
        - Upper Extremities: model-doc/03-upper-extremities.md
        - Thorax and Abdomen: model-doc/04-thorax-and-abdomen.md
        - Pelvis and Lower Extremities: 'model-doc/05-pelvis-and-lower-extremities.md'
        - Control Card Guidelines: 'model-doc/06-control-card-guidelines.md'
    - Contributor Guide:
        - 'How to Contribute': contributor-guide/01-how-to-contribute.md
        - 'Git Basics and Collaborative Development': contributor-guide/02-git-basics.md
        - 'Postprocessing simulations': 'contributor-guide/10-Postprocessing.md'
        - 'Advanced Git Functions': contributor-guide/50-advanced-git-functions.md

theme:
    name: 'material'
    palette:
        primary: 'blue grey'
        accent: 'yellow'
    logo: #'images/VIRTUAL.png'
        icon: 'directions_walk'
        # Find more at https://material.io/resources/icons/
    favicon: 'images/favicon.ico'
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex
  - admonition

plugins:
  - bibtex:
      bib_file: "viva-refs.bib"
      cite_style: "pandoc"

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
