site_name: VIVA Plus Human Body Models
site_url: https://
site_description: Project documentation
site_author: VIVA Plus Team


nav:
    - Home: index.md
    - User Guide:
        - Getting Started: user-guide/getting-started.md
        - Model Data Structure: user-guide/model-data-structure.md
    - Model:
        - Anthropometry: model-doc/anthro.md
        - Head-Neck: model-doc/head-neck.md
        - Upper Extremities: model-doc/upper-extremities.md
        - Thorax and Abdomen: model-doc/thorax-and-abdomen.md
        - Pelvis and Lower Extremities: model-doc/pelvis-and-lower-extremities.md
    - Contributor Guide:
        - Getting Started with Git: contributor-guide/getting-started-with-git.md
        - Contribute to Documentation: contributor-guide/contribute-to-documentation.md
theme: readthedocs
